### ISSUE TITLE
appveyor failed

### ISSUE THREAD

**Issue by croth1** [conda-forge/seaborn-feedstock#1]
@jakirkham - Builds for windows failed. Could you restart them for me please?

**Comment by jakirkham** [comment]
Sure. Restarted. Please let me know if you have more issues.

Note that this general upload problem is being tracked in issue ( https://github.com/conda-forge/status/issues/4 ) and seems to be caused by some problem with [Anaconda.org](https://anaconda.org/) itself. This is raised upstream as issue ( https://github.com/Anaconda-Platform/support/issues/60 ).
